"""updated account model

Revision ID: 7dd6881f338b
Revises: 3050d6667a82
Create Date: 2024-11-26 14:33:35.003224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd6881f338b'
down_revision = '3050d6667a82'
branch_labels = None
depends_on = None


revision = '7dd6881f338b'
down_revision = '3050d6667a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_account_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_account_account_number', ['account_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('fk_account_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_account_number', type_='unique')
    # ### end Alembic commands ###
